# Generated by Django 3.2 on 2021-04-12 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=30)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
